[functions.mercado-pago-webhook]
verify_jwt = false

[functions.reconcile-payment-checkout]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

[functions.validate-google-purchase]
verify_jwt = true
