import {
  ArrowLeft,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Bookmark,
  BookmarkCheck,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardCheck,
  Clock3,
  Compass,
  Crown,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  Info,
  Infinity as InfinityIcon,
  KeyRound,
  Layers3,
  LayoutDashboard,
  Library,
  ListChecks,
  LockKeyhole,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Moon,
  MoreHorizontal,
  Pause,
  PenLine,
  Play,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  StickyNote,
  Sun,
  Target,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  User,
  UserPlus,
  WalletCards,
  X,
  XCircle,
  Zap,
  createIcons,
} from 'lucide';

const icons = {
  ArrowLeft, Award, BarChart3, Bell, BookOpen, Bookmark, BookmarkCheck,
  BriefcaseBusiness, Building2, CalendarDays, Check, CheckCircle2, ChevronDown,
  ChevronRight, ChevronUp, Circle, ClipboardCheck, Clock3, Compass, Crown,
  ExternalLink, Eye, EyeOff, FileText, Filter, Flag, GraduationCap, Headphones,
  Heart, Home, Info, Infinity: InfinityIcon, KeyRound, Layers3, LayoutDashboard,
  Library, ListChecks, LockKeyhole, LogOut, Mail, MapPin, Menu, MessageCircle,
  Moon, MoreHorizontal, Pause, PenLine, Play, RotateCcw, Save, Search, Send,
  Settings, ShieldCheck, SlidersHorizontal, Sparkles, Star, StickyNote, Sun,
  Target, Timer, Trash2, TrendingUp, Trophy, User, UserPlus, WalletCards, X,
  XCircle, Zap,
};

export function hydrateIcons(root: Element | Document | DocumentFragment = document): void {
  createIcons({
    icons,
    root,
    attrs: {
      width: 20,
      height: 20,
      'stroke-width': 1.8,
      'aria-hidden': 'true',
    },
  });
}
