import {
  Archive,
  Accessibility,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Award,
  BarChart3,
  Bell,
  BellOff,
  BookOpen,
  BookOpenCheck,
  Bookmark,
  BookmarkCheck,
  Brain,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  CalendarRange,
  ChartNoAxesColumnIncreasing,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  CircleCheck,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardCheck,
  Clock3,
  Compass,
  Contrast,
  CreditCard,
  Crosshair,
  Crown,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flame,
  Flag,
  Footprints,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  Info,
  Infinity as InfinityIcon,
  KeyRound,
  Layers3,
  LayoutDashboard,
  Library,
  ListChecks,
  LockKeyhole,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Medal,
  MessageCircle,
  Moon,
  MoreHorizontal,
  PanelsTopLeft,
  Pause,
  Pencil,
  PenLine,
  Phone,
  Play,
  Plus,
  RotateCcw,
  Route,
  Ribbon,
  Save,
  Search,
  Send,
  Settings,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  StarHalf,
  StickyNote,
  Sun,
  Target,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  Diamond,
  Dumbbell,
  User,
  UserRound,
  UserPlus,
  WalletCards,
  X,
  XCircle,
  Zap,
  createIcons,
} from 'lucide';

const icons = {
  Accessibility, Archive, ArrowDown, ArrowLeft, ArrowRight, Award, BarChart3,
  Bell, BellOff, BookOpen,
  BookOpenCheck, Bookmark, BookmarkCheck, Brain, BriefcaseBusiness, Building2,
  CalendarDays, CalendarRange, ChartNoAxesColumnIncreasing, ChartNoAxesCombined,
  Check, CheckCircle2, ChevronDown, ChevronRight, ChevronUp, Circle, CircleCheck,
  ClipboardCheck, Clock3, Compass, Contrast, CreditCard, Crosshair, Crown,
  Diamond, Dumbbell, ExternalLink, Eye, EyeOff, FileText, Filter, Flame, Flag, Footprints,
  GraduationCap, Headphones,
  Heart, Home, Info, Infinity: InfinityIcon, KeyRound, Layers3, LayoutDashboard,
  Library, ListChecks, LockKeyhole, LogOut, Mail, MapPin, Medal, Menu,
  MessageCircle, Moon, MoreHorizontal, PanelsTopLeft, Pause, Pencil, PenLine,
  Phone, Play, Plus, Ribbon, RotateCcw, Route, Save, Search, Send, Settings,
  Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Star, StarHalf, StickyNote,
  Sun, Target, ThumbsUp, Timer, Trash2, TrendingUp, Trophy, User,
  UserPlus, UserRound, WalletCards, X, XCircle, Zap,
};

export function hydrateIcons(root: Element | Document | DocumentFragment = document): void {
  createIcons({
    icons,
    root,
    attrs: {
      width: 20,
      height: 20,
      'stroke-width': 1.8,
      'aria-hidden': 'true',
    },
  });
}
